/**
 * GENERATED by ui/scripts/generate-schema-parity.mjs — do not edit.
 *
 * Compile-time parity between the hand-written API types and the OpenAPI
 * schema exported from the FastAPI app (#165). A failure here means a
 * Pydantic model and its TypeScript mirror have drifted: regenerate with
 * `make generate-types`, then reconcile the type the compiler names.
 *
 * Type-only. Emits no runtime code.
 */

import type { components } from "@/lib/api/schema.generated"
import type {
  AerospikeRole,
  AerospikeUser,
  ChangePasswordRequest,
  CreateRoleRequest,
  CreateUserRequest,
  Privilege,
} from "@/lib/types/admin"
import type {
  ClusterInfo,
  ClusterNode,
  CreateNamespaceRequest,
  NamespaceInfo,
  SetInfo,
} from "@/lib/types/cluster"
import type {
  ConnectionProfileResponse,
  CreateConnectionRequest,
  TestConnectionRequest,
  TestConnectionResponse,
  UpdateConnectionRequest,
} from "@/lib/types/connection"
import type {
  UpsertGuideRequest,
} from "@/lib/types/guide"
import type {
  CreateIndexRequest,
  SecondaryIndex,
} from "@/lib/types/index"
import type {
  ACLConfig,
  ACLRoleSpec,
  ACLUserSpec,
  AerospikeNamespaceConfig,
  AerospikeNamespaceStorage,
  AerospikeVolumeAttachment,
  BandwidthConfig,
  CloneClusterRequest,
  ClusterHealthResponse,
  CreateK8sClusterRequest,
  CreateK8sTemplateRequest,
  HPACondition,
  HPAConfig,
  HPAResponse,
  HPAStatus,
  ImportClusterRequest,
  K8sClusterCondition,
  K8sClusterDetail,
  K8sClusterEvent,
  K8sClusterListResponse,
  K8sClusterSummary,
  K8sPodStatus,
  K8sTemplateDetail,
  K8sTemplateSummary,
  LoadBalancerSpec,
  MonitoringConfig,
  NetworkAccessConfig,
  NetworkPolicyAutoConfig,
  NodeBlocklistRequest,
  OperationRequest,
  OperationStatusResponse,
  PVCInfo,
  PersistentVolumeClaimSource,
  PodMetadataConfig,
  PodSchedulingConfig,
  PrometheusRuleConfig,
  RackAwareConfig,
  RackConfig,
  RackDistribution,
  RackPodSpecConfig,
  RackStorageConfig,
  ResourceConfig,
  ResourceSpec,
  RollingUpdateConfig,
  ScaleK8sClusterRequest,
  SeedsFinderServicesConfig,
  ServiceMetadataConfig,
  ServiceMonitorConfig,
  SidecarConfig,
  StorageSpec,
  StorageVolumeConfig,
  TemplateNetworkConfig,
  TemplateOverrides,
  TemplateRackConfig,
  TemplateRefConfig,
  TemplateSchedulingConfig,
  TemplateServiceConfig,
  TemplateSnapshotStatus,
  TemplateStorageConfig,
  TolerationConfig,
  UpdateK8sClusterRequest,
  UpdateK8sTemplateRequest,
  ValidationPolicyConfig,
  VolumeAttachment,
  VolumeSpec,
} from "@/lib/types/k8s"
import type {
  ClusterMetrics,
  MetricPoint,
  MetricSeries,
  NamespaceMetrics,
} from "@/lib/types/metrics"
import type {
  RecordNote,
  SetNote,
  UpsertRecordNoteRequest,
  UpsertSetNoteRequest,
} from "@/lib/types/note"
import type {
  BinDataType,
  FilterCondition,
  FilterGroup,
  FilterOperator,
  FilteredQueryRequest,
  FilteredQueryResponse,
  QueryPredicate,
  QueryRequest,
  QueryResponse,
} from "@/lib/types/query"
import type {
  AerospikeRecord,
  RecordKey,
  RecordListResponse,
  RecordMeta,
  RecordWriteRequest,
} from "@/lib/types/record"
import type {
  CreateSampleDataRequest,
  CreateSampleDataResponse,
} from "@/lib/types/sample-data"
import type {
  UDFModule,
  UploadUDFRequest,
} from "@/lib/types/udf"
import type {
  CreateWorkspaceRequest,
  UpdateWorkspaceRequest,
  WorkspaceResponse,
} from "@/lib/types/workspace"

type Schemas = components["schemas"]

/** Fails to compile unless `T` is `true`. */
type Assert<_T extends true> = never

/** `true` when A is assignable to B. */
type Extends<A, B> = A extends B ? true : false

export type Parity_AerospikeRole = Assert<Extends<AerospikeRole, Schemas["AerospikeRole"]>>
export type Parity_AerospikeUser = Assert<Extends<AerospikeUser, Schemas["AerospikeUser"]>>
export type Parity_ChangePasswordRequest = Assert<Extends<ChangePasswordRequest, Schemas["ChangePasswordRequest"]>>
export type Parity_CreateRoleRequest = Assert<Extends<CreateRoleRequest, Schemas["CreateRoleRequest"]>>
export type Parity_CreateUserRequest = Assert<Extends<CreateUserRequest, Schemas["CreateUserRequest"]>>
export type Parity_Privilege = Assert<Extends<Privilege, Schemas["Privilege"]>>
export type Parity_ClusterInfo = Assert<Extends<ClusterInfo, Schemas["ClusterInfo"]>>
export type Parity_ClusterNode = Assert<Extends<ClusterNode, Schemas["ClusterNode"]>>
export type Parity_CreateNamespaceRequest = Assert<Extends<CreateNamespaceRequest, Schemas["CreateNamespaceRequest"]>>
export type Parity_NamespaceInfo = Assert<Extends<NamespaceInfo, Schemas["NamespaceInfo"]>>
export type Parity_SetInfo = Assert<Extends<SetInfo, Schemas["SetInfo"]>>
export type Parity_ConnectionProfileResponse = Assert<Extends<ConnectionProfileResponse, Schemas["ConnectionProfileResponse"]>>
export type Parity_CreateConnectionRequest = Assert<Extends<CreateConnectionRequest, Schemas["CreateConnectionRequest"]>>
export type Parity_TestConnectionRequest = Assert<Extends<TestConnectionRequest, Schemas["TestConnectionRequest"]>>
export type Parity_TestConnectionResponse = Assert<Extends<TestConnectionResponse, Schemas["TestConnectionResponse"]>>
export type Parity_UpdateConnectionRequest = Assert<Extends<UpdateConnectionRequest, Schemas["UpdateConnectionRequest"]>>
export type Parity_UpsertGuideRequest = Assert<Extends<UpsertGuideRequest, Schemas["UpsertGuideRequest"]>>
export type Parity_CreateIndexRequest = Assert<Extends<CreateIndexRequest, Schemas["CreateIndexRequest"]>>
export type Parity_SecondaryIndex = Assert<Extends<SecondaryIndex, Schemas["SecondaryIndex"]>>
export type Parity_ACLConfig = Assert<Extends<ACLConfig, Schemas["ACLConfig"]>>
export type Parity_ACLRoleSpec = Assert<Extends<ACLRoleSpec, Schemas["ACLRoleSpec"]>>
export type Parity_ACLUserSpec = Assert<Extends<ACLUserSpec, Schemas["ACLUserSpec"]>>
export type Parity_AerospikeNamespaceConfig = Assert<Extends<AerospikeNamespaceConfig, Schemas["AerospikeNamespaceConfig"]>>
export type Parity_AerospikeNamespaceStorage = Assert<Extends<AerospikeNamespaceStorage, Schemas["AerospikeNamespaceStorage"]>>
export type Parity_AerospikeVolumeAttachment = Assert<Extends<AerospikeVolumeAttachment, Schemas["AerospikeVolumeAttachment"]>>
export type Parity_BandwidthConfig = Assert<Extends<BandwidthConfig, Schemas["BandwidthConfig"]>>
export type Parity_CloneClusterRequest = Assert<Extends<CloneClusterRequest, Schemas["CloneClusterRequest"]>>
export type Parity_ClusterHealthResponse = Assert<Extends<ClusterHealthResponse, Schemas["ClusterHealthResponse"]>>
export type Parity_CreateK8sClusterRequest = Assert<Extends<CreateK8sClusterRequest, Schemas["CreateK8sClusterRequest"]>>
export type Parity_CreateK8sTemplateRequest = Assert<Extends<CreateK8sTemplateRequest, Schemas["CreateK8sTemplateRequest"]>>
export type Parity_HPACondition = Assert<Extends<HPACondition, Schemas["HPACondition"]>>
export type Parity_HPAConfig = Assert<Extends<HPAConfig, Schemas["HPAConfig"]>>
export type Parity_HPAResponse = Assert<Extends<HPAResponse, Schemas["HPAResponse"]>>
export type Parity_HPAStatus = Assert<Extends<HPAStatus, Schemas["HPAStatus"]>>
export type Parity_ImportClusterRequest = Assert<Extends<ImportClusterRequest, Schemas["ImportClusterRequest"]>>
export type Parity_K8sClusterCondition = Assert<Extends<K8sClusterCondition, Schemas["K8sClusterCondition"]>>
export type Parity_K8sClusterDetail = Assert<Extends<K8sClusterDetail, Schemas["K8sClusterDetail"]>>
export type Parity_K8sClusterEvent = Assert<Extends<K8sClusterEvent, Schemas["K8sClusterEvent"]>>
export type Parity_K8sClusterListResponse = Assert<Extends<K8sClusterListResponse, Schemas["K8sClusterListResponse"]>>
export type Parity_K8sClusterSummary = Assert<Extends<K8sClusterSummary, Schemas["K8sClusterSummary"]>>
export type Parity_K8sPodStatus = Assert<Extends<K8sPodStatus, Schemas["K8sPodStatus"]>>
export type Parity_K8sTemplateDetail = Assert<Extends<K8sTemplateDetail, Schemas["K8sTemplateDetail"]>>
export type Parity_K8sTemplateSummary = Assert<Extends<K8sTemplateSummary, Schemas["K8sTemplateSummary"]>>
export type Parity_LoadBalancerSpec = Assert<Extends<LoadBalancerSpec, Schemas["LoadBalancerSpec"]>>
export type Parity_MonitoringConfig = Assert<Extends<MonitoringConfig, Schemas["MonitoringConfig"]>>
export type Parity_NetworkAccessConfig = Assert<Extends<NetworkAccessConfig, Schemas["NetworkAccessConfig"]>>
export type Parity_NetworkPolicyAutoConfig = Assert<Extends<NetworkPolicyAutoConfig, Schemas["NetworkPolicyAutoConfig"]>>
export type Parity_NodeBlocklistRequest = Assert<Extends<NodeBlocklistRequest, Schemas["NodeBlocklistRequest"]>>
export type Parity_OperationRequest = Assert<Extends<OperationRequest, Schemas["OperationRequest"]>>
export type Parity_OperationStatusResponse = Assert<Extends<OperationStatusResponse, Schemas["OperationStatusResponse"]>>
export type Parity_PVCInfo = Assert<Extends<PVCInfo, Schemas["PVCInfo"]>>
export type Parity_PersistentVolumeClaimSource = Assert<Extends<PersistentVolumeClaimSource, Schemas["PersistentVolumeClaimSource"]>>
export type Parity_PodMetadataConfig = Assert<Extends<PodMetadataConfig, Schemas["PodMetadataConfig"]>>
export type Parity_PodSchedulingConfig = Assert<Extends<PodSchedulingConfig, Schemas["PodSchedulingConfig"]>>
export type Parity_PrometheusRuleConfig = Assert<Extends<PrometheusRuleConfig, Schemas["PrometheusRuleConfig"]>>
export type Parity_RackAwareConfig = Assert<Extends<RackAwareConfig, Schemas["RackAwareConfig"]>>
export type Parity_RackConfig = Assert<Extends<RackConfig, Schemas["RackConfig"]>>
export type Parity_RackDistribution = Assert<Extends<RackDistribution, Schemas["RackDistribution"]>>
export type Parity_RackPodSpecConfig = Assert<Extends<RackPodSpecConfig, Schemas["RackPodSpecConfig"]>>
export type Parity_RackStorageConfig = Assert<Extends<RackStorageConfig, Schemas["RackStorageConfig"]>>
export type Parity_ResourceConfig = Assert<Extends<ResourceConfig, Schemas["ResourceConfig"]>>
export type Parity_ResourceSpec = Assert<Extends<ResourceSpec, Schemas["ResourceSpec"]>>
export type Parity_RollingUpdateConfig = Assert<Extends<RollingUpdateConfig, Schemas["RollingUpdateConfig"]>>
export type Parity_ScaleK8sClusterRequest = Assert<Extends<ScaleK8sClusterRequest, Schemas["ScaleK8sClusterRequest"]>>
export type Parity_SeedsFinderServicesConfig = Assert<Extends<SeedsFinderServicesConfig, Schemas["SeedsFinderServicesConfig"]>>
export type Parity_ServiceMetadataConfig = Assert<Extends<ServiceMetadataConfig, Schemas["ServiceMetadataConfig"]>>
export type Parity_ServiceMonitorConfig = Assert<Extends<ServiceMonitorConfig, Schemas["ServiceMonitorConfig"]>>
export type Parity_SidecarConfig = Assert<Extends<SidecarConfig, Schemas["SidecarConfig"]>>
export type Parity_StorageSpec = Assert<Extends<StorageSpec, Schemas["StorageSpec"]>>
export type Parity_StorageVolumeConfig = Assert<Extends<StorageVolumeConfig, Schemas["StorageVolumeConfig"]>>
export type Parity_TemplateNetworkConfig = Assert<Extends<TemplateNetworkConfig, Schemas["TemplateNetworkConfig"]>>
export type Parity_TemplateOverrides = Assert<Extends<TemplateOverrides, Schemas["TemplateOverrides"]>>
export type Parity_TemplateRackConfig = Assert<Extends<TemplateRackConfig, Schemas["TemplateRackConfig"]>>
export type Parity_TemplateRefConfig = Assert<Extends<TemplateRefConfig, Schemas["TemplateRefConfig"]>>
export type Parity_TemplateSchedulingConfig = Assert<Extends<TemplateSchedulingConfig, Schemas["TemplateSchedulingConfig"]>>
export type Parity_TemplateServiceConfig = Assert<Extends<TemplateServiceConfig, Schemas["TemplateServiceConfig"]>>
export type Parity_TemplateSnapshotStatus = Assert<Extends<TemplateSnapshotStatus, Schemas["TemplateSnapshotStatus"]>>
export type Parity_TemplateStorageConfig = Assert<Extends<TemplateStorageConfig, Schemas["TemplateStorageConfig"]>>
export type Parity_TolerationConfig = Assert<Extends<TolerationConfig, Schemas["TolerationConfig"]>>
export type Parity_UpdateK8sClusterRequest = Assert<Extends<UpdateK8sClusterRequest, Schemas["UpdateK8sClusterRequest"]>>
export type Parity_UpdateK8sTemplateRequest = Assert<Extends<UpdateK8sTemplateRequest, Schemas["UpdateK8sTemplateRequest"]>>
export type Parity_ValidationPolicyConfig = Assert<Extends<ValidationPolicyConfig, Schemas["ValidationPolicyConfig"]>>
export type Parity_VolumeAttachment = Assert<Extends<VolumeAttachment, Schemas["VolumeAttachment"]>>
export type Parity_VolumeSpec = Assert<Extends<VolumeSpec, Schemas["VolumeSpec"]>>
export type Parity_ClusterMetrics = Assert<Extends<ClusterMetrics, Schemas["ClusterMetrics"]>>
export type Parity_MetricPoint = Assert<Extends<MetricPoint, Schemas["MetricPoint"]>>
export type Parity_MetricSeries = Assert<Extends<MetricSeries, Schemas["MetricSeries"]>>
export type Parity_NamespaceMetrics = Assert<Extends<NamespaceMetrics, Schemas["NamespaceMetrics"]>>
export type Parity_RecordNote = Assert<Extends<RecordNote, Schemas["RecordNote"]>>
export type Parity_SetNote = Assert<Extends<SetNote, Schemas["SetNote"]>>
export type Parity_UpsertRecordNoteRequest = Assert<Extends<UpsertRecordNoteRequest, Schemas["UpsertRecordNoteRequest"]>>
export type Parity_UpsertSetNoteRequest = Assert<Extends<UpsertSetNoteRequest, Schemas["UpsertSetNoteRequest"]>>
export type Parity_BinDataType = Assert<Extends<BinDataType, Schemas["BinDataType"]>>
export type Parity_FilterCondition = Assert<Extends<FilterCondition, Schemas["FilterCondition"]>>
export type Parity_FilterGroup = Assert<Extends<FilterGroup, Schemas["FilterGroup"]>>
export type Parity_FilterOperator = Assert<Extends<FilterOperator, Schemas["FilterOperator"]>>
export type Parity_FilteredQueryRequest = Assert<Extends<FilteredQueryRequest, Schemas["FilteredQueryRequest"]>>
export type Parity_FilteredQueryResponse = Assert<Extends<FilteredQueryResponse, Schemas["FilteredQueryResponse"]>>
export type Parity_QueryPredicate = Assert<Extends<QueryPredicate, Schemas["QueryPredicate"]>>
export type Parity_QueryRequest = Assert<Extends<QueryRequest, Schemas["QueryRequest"]>>
export type Parity_QueryResponse = Assert<Extends<QueryResponse, Schemas["QueryResponse"]>>
export type Parity_AerospikeRecord = Assert<Extends<AerospikeRecord, Schemas["AerospikeRecord"]>>
export type Parity_RecordKey = Assert<Extends<RecordKey, Schemas["RecordKey"]>>
export type Parity_RecordListResponse = Assert<Extends<RecordListResponse, Schemas["RecordListResponse"]>>
export type Parity_RecordMeta = Assert<Extends<RecordMeta, Schemas["RecordMeta"]>>
export type Parity_RecordWriteRequest = Assert<Extends<RecordWriteRequest, Schemas["RecordWriteRequest"]>>
export type Parity_CreateSampleDataRequest = Assert<Extends<CreateSampleDataRequest, Schemas["CreateSampleDataRequest"]>>
export type Parity_CreateSampleDataResponse = Assert<Extends<CreateSampleDataResponse, Schemas["CreateSampleDataResponse"]>>
export type Parity_UDFModule = Assert<Extends<UDFModule, Schemas["UDFModule"]>>
export type Parity_UploadUDFRequest = Assert<Extends<UploadUDFRequest, Schemas["UploadUDFRequest"]>>
export type Parity_CreateWorkspaceRequest = Assert<Extends<CreateWorkspaceRequest, Schemas["CreateWorkspaceRequest"]>>
export type Parity_UpdateWorkspaceRequest = Assert<Extends<UpdateWorkspaceRequest, Schemas["UpdateWorkspaceRequest"]>>
export type Parity_WorkspaceResponse = Assert<Extends<WorkspaceResponse, Schemas["WorkspaceResponse"]>>
